### ISSUE TITLE
pygments_style seems to be overwritten

### ISSUE THREAD

**Issue by katosh** [TDKorn/sphinx-github-style#3]
Hi, thanks for the great sphinx extension.

I recently experience that my `pygments_style` option seems to be overwritten by sphinx_github_style. Even though I specify `pygments_style = "tango"` [here](https://github.com/settylab/Mellon/blob/43779bf4f09485ad244274c016e416119bf3dcd2/docs/source/conf.py#L71) the code boxes appear to have the dark sphinx_github_style background even when the furo theme is in light mode [here](https://mellon.readthedocs.io/en/latest/index.html).

Previously, the code boxes would use the tango style if explicitly specified as suggested [here](https://github.com/TDKorn/sphinx-github-style/issues/1). I first noticed the change a few weeks ago.

Is there still a way to use the tango pygments_style in conjunction with sphinx_github_style?

**Comment by TDKorn** [comment]
Hey again, thanks for letting me know! It looks like sphinx `v7.3.0` changed the way config values are initialized (probably here https://github.com/sphinx-doc/sphinx/issues/11855), it was released a month ago so that seems to line up. 

Can you please try installing `v1.2.2` of the extension and let me know if that fixes the issue?

**Comment by katosh** [comment]
That does it! Thank you for the quick fix!!

s. https://mellon.readthedocs.io/en/latest/

**Comment by TDKorn** [comment]
Great!!
